global:
  registry: docker.io/daprio
  logAsJson: true
  ha:
    enabled: true
    replicaCount: 3
  mtls:
    enabled: true
dapr_rbac: {}
dapr_operator:
  watchInterval: 3m
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 1024Mi
      cpu: '1'
dapr_sidecar_injector:
  resources:
    requests:
      memory: 60Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: '1'
dapr_sentry:
  resources:
    requests:
      memory: 60Mi
      cpu: 100m
    limits:
      memory: 1024Mi
      cpu: '1'
dapr_placement:
  resources:
    requests:
      memory: 75Mi
      cpu: 250m
    limits:
      memory: 1024Mi
      cpu: '1'
# dapr_scheduler: # only needed for 1.14+
#   resources:
#     requests:
#       memory: 250Mi
#       cpu: 250m
#     limits:
#       memory: 1024Mi
#       cpu: '1'